language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.1
script:
  - cd 
  - dotnet restore
  - dotnet build --configuration Release --no-restore
  - dotnet test --no-restore --verbosity normal